steps:
  - label: ":windows: :electron: Package ia32"
    command:
      - ".\\src\\buildkite-upload-script\\electron\\.buildkite\\windows\\build-and-upload-release ia32"
    agents:
      os: "windows"
      queue: "electron-build-v11"

  - label: ":windows: :electron: Package x64"
    command:
      - ".\\src\\buildkite-upload-script\\electron\\.buildkite\\windows\\build-and-upload-release x64"
    agents:
      os: "windows"
      queue: "electron-build-v11"

  - label: ":linux: :electron: Package"
    command:
      - ".buildkite/nix/build-and-upload-release.sh linux x64"
    agents:
      os: "linux"
      queue: "electron-release-v11"
  - label: ":mac: :electron: Package x64"
    command:
      - ".buildkite/nix/build-and-upload-release.sh darwin x64"
    agents:
      os: "darwin"
      queue: "electron-build-v11"
  - label: ":mac: :electron: Package arm64"
    command:
      - ".buildkite/nix/build-and-upload-release.sh darwin arm64"
    agents:
      os: "darwin"
      queue: "electron-arm-v11"

  - wait
  
  - label: ":github: Release on Github"
    command:
      - ".buildkite/release-and-publish.sh"
    agents:
      os: "darwin"
      queue: "electron-build-v11"
